#!/bin/sh
set -e
lb config noauto \
  --mode kali \
  --architectures amd64 \
  --distribution kali-rolling \
  --parent-distribution kali-rolling \
  --archive-areas "main contrib non-free non-free-firmware" \
  --parent-mirror-bootstrap http://http.kali.org/kali \
  --parent-mirror-chroot http://http.kali.org/kali \
  --parent-mirror-binary http://http.kali.org/kali \
  --mirror-bootstrap http://http.kali.org/kali \
  --mirror-chroot http://http.kali.org/kali \
  --mirror-binary http://http.kali.org/kali \
  --keyring-packages kali-archive-keyring \
  --security false \
  --updates false \
  --backports false \
  --binary-images iso-hybrid \
  --bootloaders "syslinux,grub-efi" \
  --linux-flavours "6.6.52-vitos" \
  --linux-packages linux-image \
  --debian-installer false \
  --memtest none \
  --iso-application "VITOS" \
  --iso-volume "VITOS-V1" \
  --iso-publisher "VIT" \
  --bootappend-live "boot=live components quiet splash plymouth.enable=1 username=student" \
  "${@}"
